# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: connector
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- 
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GPG_TTY=$(tty)
  
  binary: connector

  flags:
    - -tags={.Tag}
 
  goos:
    - linux
    - darwin
    - windows

  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 7

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
    - shipyardrun/connector:{{ .Tag }}
    - shipyardrun/connector:dev