---
apiVersion: v1
kind: Namespace
metadata:
  name: shipyard-test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-creator-test
  namespace: shipyard-test
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: service-creator-global-test
  namespace: shipyard-test
subjects:
  - kind: ServiceAccount
    name: connector
    namespace: shipyard-test
roleRef:
  kind: ClusterRole
  name: service-creator-test
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connector
  namespace: shipyard-test
