name: Build
on: [push]
jobs:
  build:
    env:
      GONOSUMDB: "github.com/moby/moby"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t ./...

      - name: Unit Test
        run: |
          make unit_test

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.139.0
          args: release --rm-dist --snapshot

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # required

      - uses: actions/upload-artifact@v2
        with:
          name: connector
          path: |
            ./dist
            ./dist/*.tar.gz

  functional_test:
    name: Functional Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Download the built artifacts
        uses: actions/download-artifact@v2
        with:
          name: connector

      - name: Install Shipyard
        run: |
          curl https://shipyard.run/install | bash
          echo "${GITHUB_WORKSPACE}/connector_linux_amd64" >> $GITHUB_PATH


      - name: Run Manual tests
        run: |
          cd test/simple
          shipyard run
          curl -k https://localhost:9091/expose -d \
            '{
              "name":"test1",
              "source_port": 13000,
              "remote_connector_addr": "remote-connector.container.shipyard.run:9092",
              "destination_addr": "local-service.container.shipyard.run:9094",
              "type": "local"
            }'
          sleep 5
          docker ps -a
          docker logs local-connector.container.shipyard.run
          docker logs remote-connector.container.shipyard.run
          curl -v http://localhost:13000

      - name: Run Simple Container Tests
        run: |
          cd test/simple
          shipyard test

      - name: Run Kubernetes Tests
        run: |
          cd test/kubernetes
          shipyard test
