---

name: Build
on: [push]
jobs:
  build:
    env:
      GONOSUMDB: "github.com/moby/moby"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          make setup
          go get -v -t ./...

      - name: Unit Test
        run: |
          make unit_test

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.139.0
          args: release --rm-dist --snapshot

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # required

      - uses: actions/upload-artifact@v2
        with:
          name: connector
          path: |
            ./dist
            ./dist/*.tar.gz

  functional_test:
    name: Functional Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [
          './test/simple',
          './test/kubernetes',
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.139.0
          args: release --rm-dist --snapshot

      - name: Install Deps
        run: |
          curl https://shipyard.run/install | bash
          echo "${GITHUB_WORKSPACE}/dist/connector_linux_amd64" >> $GITHUB_PATH
          chmod +x ${GITHUB_WORKSPACE}/dist/connector_linux_amd64/connector
          docker tag gcr.io/shipyard-287511/connector:dev registry.shipyard.run/connector:dev

      - name: ${{ matrix.folder }}
        run: |
          cd ${{ matrix.folder }}
          shipyard test
