name: goreleaser

on:
  push:
    tags:
       - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      
      -
        name: Docker Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin 
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.139.0
          args: release --rm-dist
