name: Release

on:
  push:
    tags:
       - 'v*'
    branches:
      - 'dev'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Build
        run: |
          make snapshot
      
      - uses: actions/upload-artifact@v2
        with:
          name: connector
          path: |
            ./dist
      
      -
        name: Setup Docker Multi-Arch Builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multi
          docker buildx use multi
          docker buildx inspect --bootstrap

      -
        name: Build and push
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 \
            -t shipyardrun/connector:${GITHUB_REF##*/} \
            -f ./Dockerfile \
            ./dist \
            --push
