name: Release

on:
  push:
    tags:
       - 'v*'
    branches:
      - 'dev'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow

            -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.2

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.147.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Setup Docker Multi-Arch Builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multi
          docker buildx use multi
          docker buildx inspect --bootstrap

      -
        name: Build and push
        run: |
          docker buildx build --platform linux/arm/v7,linux/amd64 \
            -t gcr.io/shipyard-287511/connector:${GITHUB_REF##*/} \
            -f ./Dockerfile \
            ./dist \
            --push
