name: Release

on:
  push:
    tags:
       - 'v*'
    branches:
      - 'dev'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
       contents: read
       packages: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Build
        run: |
          make snapshot
      
      - uses: actions/upload-artifact@v2
        with:
          name: connector
          path: |
            ./dist

      -
        name: Setup Docker Multi-Arch Builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multi
          docker buildx use multi
          docker buildx inspect --bootstrap

      -
        name: Build and push
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF##*/} \
            -f ./Dockerfile \
            ./dist \
            --push

      - 
        name: Zip Artifacts
        if: github.ref != 'refs/heads/dev'
        run: |
          zip ./dist/darwin_amd64.zip ./dist/darwin_amd64/connector
          zip ./dist/linux_amd64.zip ./dist/linux_amd64/connector
          zip ./dist/darwin_arm64.zip ./dist/darwin_arm64/connector
          zip ./dist/linux_arm64.zip ./dist/linux_arm64/connector

      - 
        name: Create Release 
        if: github.ref != 'refs/heads/dev'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./dist/darwin_amd64.zip
            ./dist/linux_amd64.zip
            ./dist/darwin_arm64.zip
            ./dist/linux_arm64.zip